### ISSUE TITLE
Bug: can't link image to og:image tag

### ISSUE THREAD

**Issue by bitfactory-jurgen-jansma** [dachcom-digital/pimcore-seo#32]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | no
| RFC?             | no

When I try to link an asset to the `og:image` tag, an exception is thrown:

```
Timestamp: Thu Jul 21 2022 17:00:18 GMT+0200 (Central European Summer Time)
Status: 500 | Internal Server Error
URL: /admin/seo/meta-data/set-element-meta-data-configuration
Method: POST
Message: Warning: Trying to access array offset on value of type int
Trace: 
in /app/vendor/dachcom-digital/seo/src/SeoBundle/Helper/ArrayHelper.php:107
#0 /app/vendor/dachcom-digital/seo/src/SeoBundle/Helper/ArrayHelper.php(20): SeoBundle\Helper\ArrayHelper->cleanEmptyLocaleValues(Array)
#1 /app/vendor/dachcom-digital/seo/src/SeoBundle/MetaData/Integrator/OpenGraphIntegrator.php(82): SeoBundle\Helper\ArrayHelper->mergeLocaleAwareArrays(Array, Array, 'property')
#2 /app/vendor/dachcom-digital/seo/src/SeoBundle/Manager/ElementMetaDataManager.php(88): SeoBundle\MetaData\Integrator\OpenGraphIntegrator->validateBeforePersist('object', 1727, Array, Array)
#3 /app/vendor/dachcom-digital/seo/src/SeoBundle/Controller/Admin/MetaDataController.php(78): SeoBundle\Manager\ElementMetaDataManager->saveElementData('object', 1727, 'open_graph', Array)
#4 /app/vendor/symfony/http-kernel/HttpKernel.php(152): SeoBundle\Controller\Admin\MetaDataController->setElementMetaDataConfigurationAction(Object(Symfony\Component\HttpFoundation\Request))
#5 /app/vendor/symfony/http-kernel/HttpKernel.php(74): Symfony\Component\HttpKernel\HttpKernel->handleRaw(Object(Symfony\Component\HttpFoundation\Request), 1)
#6 /app/vendor/symfony/http-kernel/Kernel.php(202): Symfony\Component\HttpKernel\HttpKernel->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true)
#7 /app/public/index.php(35): Symfony\Component\HttpKernel\Kernel->handle(Object(Symfony\Component\HttpFoundation\Request))
#8 {main}
```

An array is expected in the ArrayHelper, but it seems that the asset ID is passed instead. 

The CMS shows everything completely fine, but it can't be saved:

<img width="1292" alt="image" src="https://user-images.githubusercontent.com/40859521/180248205-611079d5-3248-4f07-8d7a-456ab467417d.png">

**Comment by bitfactory-bas-erkes** [comment]
This bundle seems abandonned?

**Comment by solverat** [comment]
@bitfactory-jurgen-jansma fixed via https://github.com/dachcom-digital/pimcore-seo/commit/8ba27b2fb06bd24ae2c27206e5be48b46121efb1
