### ISSUE TITLE
Server 500 error: Column not found: 1054 Unknown column 's0_.release_type'

### ISSUE THREAD

**Issue by NiklasBr** [dachcom-digital/pimcore-seo#68]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | no
| RFC?             | no

After upgrading to v3.1.2 we are getting the following error a lot:

```
Timestamp: Thu Aug 15 2024 15:31:18 GMT+0200 (Central European Summer Time)
Status: 500 | 
URL: /admin/seo/meta-data/get-element-meta-data-configuration
Message: An exception occurred while executing a query: SQLSTATE[42S22]: Column not found: 1054 Unknown column 's0_.release_type' in 'where clause'
Trace: 
in /var/www/pimcore/vendor/doctrine/dbal/src/Driver/API/MySQL/ExceptionConverter.php:67
#0 /var/www/pimcore/vendor/doctrine/dbal/src/Connection.php(1939): Doctrine\DBAL\Driver\API\MySQL\ExceptionConverter->convert(Object(Doctrine\DBAL\Driver\PDO\Exception), Object(Doctrine\DBAL\Query))
#1 /var/www/pimcore/vendor/doctrine/dbal/src/Connection.php(1881): Doctrine\DBAL\Connection->handleDriverException(Object(Doctrine\DBAL\Driver\PDO\Exception), Object(Doctrine\DBAL\Query))
#2 /var/www/pimcore/vendor/doctrine/dbal/src/Connection.php(1106): Doctrine\DBAL\Connection->convertExceptionDuringQuery(Object(Doctrine\DBAL\Driver\PDO\Exception), 'SELECT COUNT(s0...', Array, Array)
#3 /var/www/pimcore/vendor/doctrine/orm/src/Query/Exec/SingleSelectExecutor.php(33): Doctrine\DBAL\Connection->executeQuery('SELECT COUNT(s0...', Array, Array, NULL)
#4 /var/www/pimcore/vendor/doctrine/orm/src/Query.php(327): Doctrine\ORM\Query\Exec\SingleSelectExecutor->execute(Object(Doctrine\DBAL\Connection), Array, Array)
#5 /var/www/pimcore/vendor/doctrine/orm/src/AbstractQuery.php(1212): Doctrine\ORM\Query->_doExecute()
#6 /var/www/pimcore/vendor/doctrine/orm/src/AbstractQuery.php(1166): Doctrine\ORM\AbstractQuery->executeIgnoreQueryCache(NULL, 4)
#7 /var/www/pimcore/vendor/doctrine/orm/src/AbstractQuery.php(991): Doctrine\ORM\AbstractQuery->execute(NULL, 4)
#8 /var/www/pimcore/vendor/doctrine/orm/src/AbstractQuery.php(1020): Doctrine\ORM\AbstractQuery->getSingleResult(4)
#9 /var/www/pimcore/vendor/dachcom-digital/seo/src/Manager/ElementMetaDataManager.php(352): Doctrine\ORM\AbstractQuery->getSingleScalarResult()
#10 /var/www/pimcore/vendor/dachcom-digital/seo/src/Manager/ElementMetaDataManager.php(47): SeoBundle\Manager\ElementMetaDataManager->elementMetaDataExistsWithReleaseType('object', 27798, 'draft')
#11 /var/www/pimcore/vendor/dachcom-digital/seo/src/Manager/ElementMetaDataManager.php(63): SeoBundle\Manager\ElementMetaDataManager->getElementData('object', 27798, true)
#12 /var/www/pimcore/vendor/dachcom-digital/seo/src/Controller/Admin/MetaDataController.php(49): SeoBundle\Manager\ElementMetaDataManager->getElementDataForBackend('object', 27798)
#13 /var/www/pimcore/vendor/symfony/http-kernel/HttpKernel.php(181): SeoBundle\Controller\Admin\MetaDataController->getElementMetaDataConfigurationAction(Object(Symfony\Component\HttpFoundation\Request))
#14 /var/www/pimcore/vendor/symfony/http-kernel/HttpKernel.php(76): Symfony\Component\HttpKernel\HttpKernel->handleRaw(Object(Symfony\Component\HttpFoundation\Request), 1)
#15 /var/www/pimcore/vendor/symfony/http-kernel/Kernel.php(197): Symfony\Component\HttpKernel\HttpKernel->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true)
#16 /var/www/pimcore/vendor/symfony/runtime/Runner/Symfony/HttpKernelRunner.php(35): Symfony\Component\HttpKernel\Kernel->handle(Object(Symfony\Component\HttpFoundation\Request))
#17 /var/www/pimcore/vendor/autoload_runtime.php(29): Symfony\Component\Runtime\Runner\Symfony\HttpKernelRunner->run()
#18 /var/www/pimcore/public/index.php(19): require_once('/var/www/pimcor...')
#19 {main}

```

**Comment by solverat** [comment]
@NiklasBr Like described [here](https://github.com/dachcom-digital/pimcore-seo/releases/tag/v3.1.0), please execute

bin/console doctrine:migrations:migrate --prefix 'SeoBundle\Migrations'
